# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01977c953ada5252aa2b2a74e4ef3680773ad1e90c6ff3c7768f4e0dfa25fecc328c888d863b22c1363c5a784dc9c6df03fe100bad003680dac41a386d78d812

test:
  secret_key_base: f72b3de957b1a0b15909dd5bf59d3101e29d43d577eeffc674def2f88d4adffcf38cdc6a129bd0923b3379046d5475c677c8adb002d6aec0c5e376b508fd64f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
